/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "downloadImage",
            "endpoint": "https://ubhfksabm4.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://d3bnildgofd27mfwqi72cehnsi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rbyjdqgd2feyphaapkmm5ali2e",
    "aws_cognito_identity_pool_id": "us-east-1:e9d06b9e-be2e-49cb-9135-74300c88da72",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Zz2FfXDdj",
    "aws_user_pools_web_client_id": "1g2ofct6g2log068j4dsonbt63",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mira-webapp-storage142735-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
